### ISSUE TITLE
Reactive validation for nested schema

### ISSUE THREAD

**Issue by gilizeevi** [aldeed/meteor-autoform#1683] opened 2018-11-10 21:30 UTC
Hello.

I'm currently facing an issue with reactive validation errors not appearing on nested subschema fields. When adding AutoForm.debug, the errors are logged but does not show on the form.

Example:
JS
```
const Tasks = new Mongo.Collection('tasks');
const SubTaskSchema = new SimpleSchema({
    subtitle: {
        type: String,
        label: "Subtitle",
        required: true
    },
    price: {
        type: String,
        label: "Price",
        required: true
    }
}, { tracker: Tracker });

const TaskSchema = new SimpleSchema({
    title: {
        type: String,
        label: "Title",
    },
    subTask: {
        type: Object
    },
    'subTask.$': {
        type: SubTaskSchema
    }
}, { tracker: Tracker });
Tasks.attachSchema(TaskSchema);
```

HTML
`{{> quickForm collection=getCollection id="insertTaskForm" type="insert"}}
`OR
```
 {{#autoForm collection=getCollection id="insertTaskForm" type="insert"}}
        <fieldset>
            <legend>Add a task</legend>
            {{> afQuickField name='title'}}
            {{> afQuickFields name='subTask.$'}}
        </fieldset>
        <button type="submit" class="btn btn-primary">Insert</button>
{{/autoForm}}
```

In the quickform example, when subtask fields are empty, a validation error of 'subtasks is required' does appear, but not for subtasks fields.

Reactive validation errors of nested subscehma did work with previous versions, before Tracker was added. Any idea what i'm doing wrong and how to solve it?

**Comment by jamgold** [comment] 2019-07-01 16:57
I notice the same behavior. Has anybody figured out how to solve this? The onError hook of the form has all validation errors in validationContext._validationErrors but just doesn't display it for a nested schema

**Comment by evolross** [comment] 2020-02-06 01:32
I get this too. Occurs when using either `quickForm` and `autoForm`.

Linking to your [work-around](https://forums.meteor.com/t/schema-validation-errors-not-showing-in-autoform/36225/14) that solves this problem for now.

**Comment by aldeed** [comment] 2020-03-24 23:59
Duplicate of https://github.com/aldeed/simple-schema-js/issues/359, which has a PR in review / discussion

**Closed as completed by aldeed** 2020-03-24 23:59 UTC
