### ISSUE TITLE
How to put HTML in afQuickField labels?

### ISSUE THREAD

**Issue by dkmooers** [aldeed/meteor-autoform#941] opened 2015-05-13 22:04 UTC
I'm trying to make a checkbox label with HTML in it:

    acceptTerms: {
		type: Boolean,
		label: 'I agree to the <a href="/terms">terms and conditions</a> and <a href="/security-policy">privacy policy</a>.',
		optional: true,
		custom: function() {
			if (!this.value) {
				return "You must accept the terms and conditions and privacy policy to create an account.";
			}
		}
	}

But that just renders escaped HTML. Is there any way around this? I tried just using afFieldInput with my own label, but afFieldInput already contains a <div> and <label> in the template.

Help?

**Comment by dkmooers** [comment] 2015-05-13 22:07
I'm trying to do it like CloudFlare does it:

https://www.cloudflare.com/a/sign-up

**Comment by andmitsch** [comment] 2015-06-01 13:38
`afFieldInput` should not render a label on its own. That's what `afFormGroup`is for.

In your case something like:
```
  <div class="form-group {{#if afFieldIsInvalid name='url'}}has-error{{/if}}">
    
   {{> afFieldInput name='terms' type="select-radio" noselect=true}}

    <label class="control-label" for="terms">I agree to the <a href="/terms">terms and conditions</a> and <a href="/security-policy">privacy policy</a></label>

    {{#if afFieldIsInvalid name='terms'}}
      <span class="help-block">You must accept the terms and conditions and privacy policy to create an account.</span>
    {{/if}}
  </div>
``` should work. Probably ;)

**Comment by andmitsch** [comment] 2015-06-01 14:05
`afInputField`renders a label automatically when you make it a selection/checkbox/radio tag.

Though, the easiest might be something like this:
```
autoform: {
  afFieldInput: {
	  type: "boolean-checkbox",
	  label: "I agree to the <a href='/terms''>terms and conditions</a> and <a href='/security-policy'>privacy policy</a>."
  }
}
```
with an afInputField markup like:

```
<div class="form-group {{#if afFieldIsInvalid name='acceptTerms'}}has-error{{/if}}">
    
	{{> afFieldInput name='acceptTerms' type="select-radio" noselect=true}}

	{{#if afFieldIsInvalid name='acceptTerms'}}
		<span class="help-block">You must accept the terms and conditions and privacy policy to create an account.</span>
	{{/if}}
</div>
```

However, you could also change the error `{{{afFieldMessage name='acceptTerms'}}}` in the simpleSchema, but don't know if it is simply using a property like `error: 'message'`

**Comment by dkmooers** [comment] 2015-06-10 19:39
@andmitsch Thanks for the suggestion! Unfortunately the label renders as plain text, not HTML:

    <label>
      <input type="checkbox" value="true" name="acceptTerms" data-schema-key="acceptTerms">
      I agree to the &lt;a href='/terms'&gt;terms and conditions&lt;/a&gt; and &lt;a href='/security-policy'&gt;privacy policy&lt;/a&gt;.
    </label>

**Comment by dkmooers** [comment] 2015-06-10 19:41
Don't know why I didn't think of the obvious solution - write the HTML myself!

Jade:

    .form-group(class="{{#if afFieldIsInvalid name='acceptTerms'}}has-error{{/if}}")
	label.control-label
		input(type="checkbox" value="true" name="acceptTerms" data-schema-key="acceptTerms").form-control
		| I agree to the <a href='/terms' target="_blank">terms and conditions</a> and <a href='/security-policy' target="_blank">privacy policy</a>.
		if afFieldIsInvalid name='acceptTerms'
			span.help-block You must accept the terms and conditions and privacy policy to create an account.

Still might be nice to have an afQuickField/afFormGroup option that was something like `labelHTML=true' that would parse the label using {{{label}}} instead of {{label}}.

**Comment by vieko** [comment] 2015-06-19 20:11
+1

**Comment by aldeed** [comment] 2015-10-06 05:35
Duplicate of #936

**Closed by aldeed** 2015-10-06 05:35 UTC

**Comment by etheleon** [comment] 2016-01-26 07:35
could someone write the jade example in html.. cant understand this

**Comment by epec254** [comment] 2016-08-20 20:13
Hope this helps someone else - this @dkmooers's code (slightly modified) in HTML.  I changed the classes to reflect what the "boolean-checkbox" in AutoForm 5.8.1 outputs by default for boostrap3.

All caps are the places you'd need to customize to your app (TOS_FIELD_NAME, PRIVACY_URL, TOS_URL)

```
<div class="form-group {{#if afFieldIsInvalid name='TOS_FIELD_NAME'}}has-error{{/if}}" data-required="true">
    <div class="checkbox">
        <label>
            <input type="checkbox" value="true" name="TOS_FIELD_NAME" data-schema-key="TOS_FIELD_NAME">By checking this box, you agree to our <a href="TOS_URL" target="_blank">Terms of Service</a> and <a href="PRIVACY_URL" target="_blank">Privacy Policy</a>
        </label>
    </div>
    {{#if afFieldIsInvalid name='TOS_FIELD_NAME' }}
    <span class="help-block"> You must accept our Terms of Service and Privacy Policy to create an account.</span> {{/if}}
</div>
```

**Comment by epec254** [comment] 2016-08-20 22:48
The issue with this approach (defining the input field manually) is that you lose the "magic" of Auto-Form's "boolean-checkbox" logic (e.g., returning true or false based on the checked property).

Slightly hack-y, but I got it to work by creating a custom component (identical to boolean-checkbox, but with the label changed).

**Template**
```
<template name="afTosCheckbox">
    <div>
        <label>
            <input type="checkbox" value="true" {{atts}} /> By checking this box, you agree to our <a href="{{pathFor 'App.termsOfService'}}" target="_blank">Terms of Service</a> and <a href="{{pathFor 'App.termsOfService'}}" target="_blank">Privacy Policy</a></label>
    </div>
</template>
```

**Code to load the add't input type (can go in startup, or your choice as long as it is loaded)**
```
AutoForm.addInputType("tos-checkbox", {
  template: "afTosCheckbox",
  valueOut: function () {
    return !!this.is(":checked");
  },
  valueConverters: {
    "string": AutoForm.valueConverters.booleanToString,
    "stringArray": AutoForm.valueConverters.booleanToStringArray,
    "number": AutoForm.valueConverters.booleanToNumber,
    "numberArray": AutoForm.valueConverters.booleanToNumberArray
  },
  contextAdjust: function (context) {
    if (context.value === true) {
      context.atts.checked = "";
    }
    //don't add required attribute to checkboxes because some browsers assume that to mean that it must be checked, which is not what we mean by "required"
    delete context.atts.required;
    return context;
  }
});
```

**Simple-schema definition for the field** 
```
  tosPrivacyAgreement: {
    type: Boolean,
    optional: true,
    autoform: {
      type: 'tos-checkbox',
    },
    allowedValues: [true],
  },
```

**if you want to get fancy, custom validation message**
```
schema.messages({
  "notAllowed tosPrivacyAgreement": TAPi18n.__('tosPrivacyAgreement.notAcceptMessage'),
};
```
