### ISSUE TITLE
Firefox: Exception from Tracker recompute function: too much recursion using quickForm

### ISSUE THREAD

**Issue by ripdog** [aldeed/meteor-autoform#333] opened 2014-09-07 01:06 UTC
This is the second time I have come across this bug in my project. Only seems to affect quickForms. I'm running firefox nightly on Win8.1 x64. Buildstring: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:35.0) Gecko/20100101 Firefox/35.0 ID:20140903072057 CSet: 5e9826980be5

(not that it matters, any version seems to have the bug.)

Here's a nastily large repro:

https://github.com/ripdog/booking-meteor/tree/toomuchrecursion

Run that and navigate to "providers" on the navbar, or add /providers to the url. Relevant code is in `client/views/providerEdit.*`. Schema is in `lib/providers.js`

Versions visible at https://github.com/ripdog/booking-meteor/blob/toomuchrecursion/.meteor/versions - 
```
aldeed:autoform@0.17.1
aldeed:collection2@0.4.6
aldeed:simple-schema@0.7.0
```
And meteor 0.9.1. Updated today.

Full Error: https://gist.github.com/ripdog/592f3f6b584abd37df01 - it's long.

**Comment by abashinyan** [comment] 2015-01-02 10:37
Hello, same problem on Arch with FF 34.0.5

**Comment by brylie** [comment] 2015-01-03 06:58
For easy reproduction and clarity, here is a [minimal example](https://github.com/brylie/meteor-quickform-recurstion):

```html
<body>
 {{> quickForm id="quickform" schema="schema"}}
</body>
```

```javascript
schema = new SimpleSchema({
    name: {
        type: String
    }
});
```
**None of the following were necessary**:
* template nesting
* arrays of field (e.g. [field])
* collection2

**Comment by der-ede** [comment] 2015-01-03 14:19
@brylie, @ChenRoth: I also think that it is not ff related, since I do not see a reason why one should recurse anything in input forms?
Recursions are if a function calls itself and is used mainly for mathematical operations like factorials e.g.

**Comment by ChenRoth** [comment] 2015-01-03 15:06
@der-ede it's not caused by an FF flaw, but is related to FF because it occurs within its limitations
Also, recursion is inherent in web development (DOM trees)

there's definitely some loose end which causes excessive mem allocation, "just" gotta find it.

**Comment by der-ede** [comment] 2015-01-03 15:20
@ChenRoth that's what I meant (also not a native web developer), cannot be that there are so many operations neccessary here. Maybe the downside of open-source, someone should open a paypal donation, I'd give 10€.

**Comment by brylie** [comment] 2015-01-03 17:50
I am stepping through the previous example using the Firefox debugger, and here are some functions I keep seeing:

* afFormGroup.html
    * Template.__checkName("afFormGroup");
* afFormGroup.js
    * Line 18: function formGroupLabelAtts(atts)
    * Line 29: function formGroupInputAtts(atts)
    * Line 1: Template.afFormGroup.helpers
* template.js
    * Line 255, 17, 21, 26, 28... It does several things in a few function calls
* afObjectField.html
    * Line 2: Template.__checkName("afObjectField");
    * Line 3: Template["afObjectField"] = new Template("Template.afObjectField", (function() {
* underscore.js
    * Line 243, 244
* templating.js
    * line 19

It just keeps looping among those files/lines.

**Comment by brylie** [comment] 2015-01-03 18:40
Sequence
-------

File Name | Line Number | Code
--------------|------------------|-------
afArrayField.html | 2 | 
templating.js | 19
underscore.js | 243 | `if (obj == null) return false;`
  | 244 | `if (nativeIndexOf && obj.indexOf === nativeIndexOf) return obj.indexOf(target) != -1;`
  | 244 | `if (nativeIndexOf && obj.indexOf === nativeIndexOf) return obj.indexOf(target) != -1;`
templating.js | 19 | `if (name in Template || _.contains(RESERVED_TEMPLATE_NAMES, name)) {`
  | 19 | `if (name in Template || _.contains(RESERVED_TEMPLATE_NAMES, name)) {`
afArrayField.html | 2
  | 3
template.js | 17
  | 21
  | 26
  | 28
  | 31
  | 32
  | 34
  | 39 | `var HelperMap = function () {};`
  | 39 | `var HelperMap = function () {};`
  | 34 | `this.__helpers = new HelperMap;`
  | 35 | ` this.__eventMaps = [];`
?? | ?? | ??
afArrayField.html | 3 | `Template["afArrayField"] = new Template("Template.afArrayField", (function() {`
afArrayField.js | 1 | `Template.afArrayField.helpers({`
  | 2 | `innerContext: function afArrayFieldContext(options) {`
  | 1 |
template.js | 256 | `for (var k in dict)`
  | 257 | `this.__helpers.set(k, dict[k]);`
  | 256 | `for (var k in dict)`
  | 257 | `this.__helpers.set(k, dict[k]);
  | 44 | `this[' '+name] = helper;`
  | 44 | `this[' '+name] = helper;`
  | 257 | `this.__helpers.set(k, dict[k]);`
  | 257 | `this.__helpers.set(k, dict[k]);`
afArrayField.js | 1 | `Template.afArrayField.helpers({`
  |1| `Template.afArrayField.helpers({`
afEachArrayItem.html | 2 | `Template.__checkName("afEachArrayItem");`
templating.js | 19 | `if (name in Template || _.contains(RESERVED_TEMPLATE_NAMES, name)) {`
underscore.js | 243 | `if (obj == null) return false;`
  | 244 | ` if (nativeIndexOf && obj.indexOf === nativeIndexOf) return obj.indexOf(target) != -1;`
  | 244 | ` if (nativeIndexOf && obj.indexOf === nativeIndexOf) return obj.indexOf(target) != -1;`
templating.js | 19 | `if (name in Template || _.contains(RESERVED_TEMPLATE_NAMES, name)) {`
afEachArrayItem.html | 2| `Template.__checkName("afEachArrayItem");`
  | 3 | `Template["afEachArrayItem"] = new Template("Template.afEachArrayItem", (function() {`
template.js | 17 | `if (! (this instanceof Blaze.Template))`
  | 21 | `if (typeof viewName === 'function') {`
  | 26 | `if (typeof viewName !== 'string')
  | 28 | `if (typeof renderFunction !== 'function')`
  | 31 | `this.viewName = viewName;`
  | 32 | `this.renderFunction = renderFunction;`
  | 34 | `this.__helpers = new HelperMap;`
  | 39 | `var HelperMap = function () {};`
  | 39 | `var HelperMap = function () {};`
  | 34 | `this.__helpers = new HelperMap;`
  | 35 | `this.__eventMaps = [];`
  | 35 | `this.__eventMaps = [];`
afEachArrayItem.html | 3 | `Template["afEachArrayItem"] = new Template("Template.afEachArrayItem", (function() {`
  | 3 | `Template["afEachArrayItem"] = new Template("Template.afEachArrayItem", (function() {`
afEachArrayItem.js | 1 | `Template.afEachArrayItem.helpers({`
  | 2 | `innerContext: function afEachArrayItemContext(options) {`
  | 1 | `Template.afEachArrayItem.helpers({`
template.js | 256 | `for (var k in dict)`
  | 257 | `this.__helpers.set(k, dict[k]);`
  | 256 | `for (var k in dict)`
  | 257 | `this.__helpers.set(k, dict[k]);`
template.js | 44 | ` this[' '+name] = helper;`
   | 44 | ` this[' '+name] = helper;`
  | 257 | see above
   | 257 | see above
afEachArrayItem.js | 1 | `Template.afEachArrayItem.helpers({`
   | 1 | see above
afFieldInput.html | 2 | `Template.__checkName("afFieldInput");`
templating.js | 19 | `if (name in Template || _.contains(RESERVED_TEMPLATE_NAMES, name)) {`
underscore.js | 243 | `if (obj == null) return false;`
  | 244 | `if (nativeIndexOf && obj.indexOf === nativeIndexOf) return obj.indexOf(target) != -1;`
   | 244 | see above
templating.js | 19 | see above
(variables change) | 19 | see above
afFieldInput.html | 2 | see above
  | 3 | see above
template.js | 17 | see above
  | 21.. 26.. 28.. 31.. 32.. 34.. 39.. 39.. 34.. 35..|

**Comment by brylie** [comment] 2015-01-03 19:12
While going through the trace above, I noticed the following message several times in my browser console (Firefox):

```
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Sat Jan 03 2015 {{time}} GMT+0200 (EET)
Full Message: InternalError: too much recursion
```

**Comment by aldeed** [comment] 2015-01-03 22:33
Could you all try running with the `ff-fix` branch of autoform? I think that fixes this recursion issue, but maybe not for all cases. I basically just removed as many `#with` blocks from the autoform templates as I could. It's possible a few more could be removed. I need to test some more to be sure nothing else broke before I can release it.

**Comment by brylie** [comment] 2015-01-04 09:41
I have tried several times to run the `ff-fix` branch with no success. I have tried:
*  Cloning the branch into the project directory
* Renaming the cloned branch folder to `lib`
* Cloning the branch into the `.meteor/local/build/programs..` folders
I keep getting *... is not defined* type errors.

```
 ReferenceError: Template is not defined
? (STDERR)     at app/lib/components/afArrayField/afArrayField.js:1:36
```

What are the steps I take to check out the branch and test it in a project?

**Comment by brylie** [comment] 2015-01-14 09:04
OK, on a fresh meteor project, how do I test the `ff-fix` branch? Specific steps would really help, as I am new to this.

E.g.

1. meteor create ff-fix-test
2. cd ff-fix-test
3. ??

**Comment by aldeed** [comment] 2015-01-14 16:12
I've tested more and the problem still exists on ff-fix branch. Still working on it.

@brylie:

1. meteor create ff-fix-test
2. cd ff-fix-test
3. cd packages
4. git clone https://github.com/aldeed/meteor-autoform.git
5. cd meteor-autoform
6. git checkout ff-fix
7. cd ../..
8. meteor add aldeed:autoform
9. meteor

**Comment by mquandalle** [comment] 2015-01-14 16:21
PS: here is a faster recipe:

```sh
$ meteor create ff-fix-test
$ cd ff-fix-test
$ git clone -b ff-fix --depth 1 https://github.com/aldeed/meteor-autoform.git packages/autoform/
$ meteor add aldeed:autoform
$ meteor
```

Sorry to be "that guy" :-)

**Comment by brylie** [comment] 2015-01-14 18:57
OK, I tested again and the form still fails to render on this [minimal example using the ff-fix branch](https://github.com/brylie/meteor-autoform-recursion-ff-fix).

In my performance audit, I noticed a few calls to remote resources including:
* ace.editor (cloudfront.net)
* plusone.js (google.com)

What are these files for?

**Comment by yogiben** [comment] 2015-01-23 11:11
I'm experiencing this using `> afQuickField`.

Running the latest version of FF on 3 OS's

The bug does not appear:
Windows 8
Mac OS X

The bug appears: 
Ubuntu 14.04

This might be a positive indication that a future FF update will fix this.

**Comment by ameesters** [comment] 2015-01-26 15:12
Can confirm this also happens outside of autoform, definitely somethings up with blaze + FF 35.0 and a custom component system.

**Comment by aldeed** [comment] 2015-01-26 17:55
Yeah, I think there is generally a lot of recursion in Blaze due to the DOM-like nature of it, but the biggest culprit seems to be `Template.dynamic`. In AF 5.0, I'm attempting to flatten a lot of the templates as much as possible, and will try alternatives to `Template.dynamic`. I'm not sure if it will be completely solvable without Blaze changes, but it should be less common.

**Comment by ameesters** [comment] 2015-01-27 08:53
We are currently looking if we can use underscore's `defer` function to circumvent the maximum call stack... maybe thats something you would be interested in to know:

>Defers invoking the function until the current call stack has cleared, similar to using setTimeout with a delay of 0. Useful for performing expensive computations or HTML rendering in chunks without blocking the UI thread from updating. If you pass the optional arguments, they will be forwarded on to the function when it is invoked.

http://underscorejs.org/#defer

**Comment by hamoid** [comment] 2015-02-02 19:09
Trying to understand what was going on I formatted the console error in Firefox like this:
http://pastebin.com/A9YF9vKv (renamed the hashes and removed redundant characters)
Looking forward to a workaround or fix for this issue.

**Comment by boustanihani** [comment] 2015-02-07 01:41
I'm getting this too using **Firefox 35.0.**1 on **Ubuntu 14.04 64bit** :(

**Comment by mgruen** [comment] 2015-02-10 09:46
Algo getting this - Firefox 35 / Ubuntu 14.04 64bit.   Simple quickform with a fairly simple structure:

Skills.attachSchema(new SimpleSchema({
    escolaridade:     { type: String,     label: "Escolaridade"  },
    nivelIngles:    { type: String,     label: "Nível de Inglês"   },
    'roles': {type: [Object]  },
    'roles.$.capacidade':       {type: String, label: "Cargo"},
    'roles.$.anosExperiencia':  {type: Number, label: "Anos de Experiencia"}
  }));

**Comment by shkomg** [comment] 2015-02-23 10:44
@aldeed Thank you for the great package! 
I'm facing this FF too much recursion too. 
Hope you have it fixed in AF 5.0. 
When do you anticipate releasing AF 5.0 ?

Thank you much!

**Comment by serkandurusoy** [comment] 2015-03-02 12:21
When I try to access http://autoform.meteor.com with firefox (latest) on ubuntu 14.04 64-bit I get this on the console:

````
"Exception from Tracker recompute function: too much recursion
l._wrapCatchingExceptions/<@http://autoform.meteor.com/0671074ec71757a1970e81101a74c36add0613a7.js:39:16328
l.call@http://autoform.meteor.com/0671074ec71757a1970e81101a74c36add0613a7.js:179:1817
l.mustacheImpl@http://autoform.meteor.com/0671074ec71757a1970e81101a74c36add0613a7.js:179:1067
l.mustache@http://autoform.meteor.com/0671074ec71757a1970e81101a74c36add0613a7.js:179:1118
c.__dynamic</<@http://autoform.meteor.com/0671074ec71757a1970e81101a74c36add0613a7.js:179:2899
a@http://autoform.meteor.com/0671074ec71757a1970e81101a74c36add0613a7.js:39:18913
a/<@http://autoform.meteor.com/0671074ec71757a1970e81101a74c36add0613a7.js:39:18017
l._withCurrentView@http://autoform.meteor.com/0671074ec71757a1970e81101a74c36add0613a7.js:39:21048
a@http://autoform.meteor.com/0671074ec71757a1970e81101a74c36add0613a7.js:39:17975
n.Computation.prototype._compute@http://autoform.meteor.com/0671074ec71757a1970e81101a74c36add0613a7.js:12:1773
n.C"[…]
````

and also this:

````
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ddp--4715-autoform.meteor.com/sockjs/info?cb=5vmqth4l3a. This can be fixed by moving the resource to the same domain or enabling CORS.
````

I should also note that I get these only on 

- quickform playground
- quickform details

pages. The other pages are fine.

On a side note, on the same browser session, some bootstrap-3 styles don't seem to be applied. Namely, radios and checkboxes appear unstyled. Other styling appear fine. May or may not be related.

**Comment by samybob1** [comment] 2015-03-06 17:40
@serkandurusoy same exception here with Mozilla Firefox 36.0 on Fedora 21, but everything is working fine with Google Chrome 41.0.2272.76

**Comment by serkandurusoy** [comment] 2015-03-06 19:04
I seem to get the same exception on one of my apps every now on then on firefox, but can't pinpoint it. If I can, I'll also share a reproduction. But I guess the official demo app can serve that purpose as well.

**Comment by CvanRijen** [comment] 2015-03-11 03:26
Ubuntu 14.04 FF, got the same problem trying to use autoform in an app.

From http://autoform.meteor.com/ all pages work fine except for /quickform which works 75% of the time and /qfdetails which I can't get to work at all.

**Comment by shtefcs** [comment] 2015-03-19 01:17
Is this bug solved with latest Meteor version ?

**Comment by serkandurusoy** [comment] 2015-03-19 12:56
http://autoform.meteor.com/ still suffers from it, but I don't know if it is the latest version.

**Comment by aldeed** [comment] 2015-03-19 14:59
The demo is on latest autoform but not latest Meteor. We'll see once I get it updated, but I don't think they did anything to resolve this in the new Meteor release.

**Comment by shtefcs** [comment] 2015-03-19 16:45
@aldeed you probably let them know about it, but seems its not enough. You have power of community cause lot of people using ur package and facing this issue. Imo you should push them harder about it with support from ur community (people who are using ur package)

**Comment by hamoid** [comment] 2015-03-19 17:16
At least I think there should be a clear warning on the package page. I'm working on a complex project, I implemented lots of forms with autoform, noticed it wasn't working on Firefox, had to undo it all and write my own solution. Much more work than if I had avoided autoform.

**Comment by abashinyan** [comment] 2015-03-19 17:35
@shtefcs "too much recursion" - Meteor 1.0.4.1, autoform 5.0.2, FF 36.0.1, Arch

**Comment by serkandurusoy** [comment] 2015-03-19 18:04
Github is great in linking issues together, and this has already been linked to another issue on meteor's core tracker, but in light of sooo many comments on this, I believe it is time we remind ourselves of this:

https://github.com/meteor/meteor/issues/3028

**Comment by SachaG** [comment] 2015-03-19 22:48
For what it's worth I always do my best to advocate to MDG that they should be more involved in the community and help out key packages maintainer like you. Hopefully after the Windows stuff is out they'll have time to do just that and address bugs like this one.

**Comment by aldeed** [comment] 2015-03-20 14:09
On the AutoForm side, I think AF 5.0 release represents all the possible improvements to recursion without deprecating features. Generally speaking, you should be able to still use autoform if you need to support Firefox on Linux, but you will have to rely less on the "magic" components. So use `autoForm` instead of `quickForm`, and use `afFormGroup`, `afArrayField`, or `afObjectField` directly instead of `afQuickField`. The more you use pure autoform instead of the "quick" components, the better it should work. For really complex forms, though, it might be tough to work around.

**Comment by shkomg** [comment] 2015-03-20 15:42
yep, I must confirm, no more "too much recursion" on simplier forms where I
have that mistake before.

2015-03-20 16:09 GMT+02:00 Eric Dobbertin <notifications@github.com>:

> On the AutoForm side, I think AF 5.0 release represents all the possible
> improvements to recursion without deprecating features. Generally speaking,
> you should be able to still use autoform if you need to support Firefox on
> Linux, but you will have to rely less on the "magic" components. So use
> autoForm instead of quickForm, and use afFormGroup, afArrayField, or
> afObjectField directly instead of afQuickField. The more you use pure
> autoform instead of the "quick" components, the better it should work. For
> really complex forms, though, it might be tough to work around.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aldeed/meteor-autoform/issues/333#issuecomment-84023765>
> .
>



-- 
Best regards

Serhiy Khvashchuk

**Comment by shtefcs** [comment] 2015-03-26 01:01
@shkomg https://github.com/meteor/meteor/issues/3028#issuecomment-86266653. Does it solve our problems ?

**Comment by aldeed** [comment] 2015-03-30 23:04
In my testing on linux, I don't see any too much recursion errors running against `meteor --release 1.1-rc.4`. Looks like MDG fixed this one!

**Closed by aldeed** 2015-03-30 23:04 UTC

**Comment by serkandurusoy** [comment] 2015-03-31 06:53
Thanks @aldeed for following up on this!

**Comment by workflow** [comment] 2015-03-31 09:46
(dance)

**Comment by der-ede** [comment] 2015-03-31 10:22
Thx
Am 31.03.2015 11:46 schrieb "Florian Peter" <notifications@github.com>:

**Comment by JanvanCasteren** [comment] 2015-10-16 20:53
@aldeed 
Did you update your demo app (http://autoform.meteor.com)? I have just been using it and unfortunately it still gives a lot of 'too much recursion' errors in Firefox on Ubuntu 14.04 and Windows 7.
