### ISSUE TITLE
Form gives wrong validation error on number field

### ISSUE THREAD

**Issue by rclai** [aldeed/meteor-autoform#882] opened 2015-04-14 16:20 UTC
```js
// schema of a number field
numberField; {
  type: Number
}
```

When I wrote a letter in the field and triggered validation, it gave me the `required` error instead of the `expectedNumber` error.

**Comment by aldeed** [comment] 2015-04-14 20:39
Duplicate of #496 and #385. Unfixable.

**Closed by aldeed** 2015-04-14 20:39 UTC
