### ISSUE TITLE
Bug in firefox 

### ISSUE THREAD

**Issue by partus** [aldeed/meteor-autoform#646] opened 2015-01-18 03:08 UTC
aldeed:autoform@4.2.2

html: 

    {{> quickForm schema=Schemas.blogSettings doc=doc  id="somecontactForm" type="method" meteormethod="setBlogSettings"}}

js:

Schemas.blogSettings = new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 200
  },
  description: {
    type: String,
    label: "Description",
    optional: true
  }
})

UI.registerHelper("Schemas", function(){
  return Schemas;
})

exception:

Exception from Tracker recompute function: too much recursion
fireCallbacks@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1835:9
Tracker.nonreactive@http://www.localhost.com:3000/packages/tracker.js?7f0c5481709a504dd2254ba2a71c1cee78adc280:513:12
Blaze._fireCallbacks/<@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1832:5
Blaze._withCurrentView@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12
Blaze._fireCallbacks@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1831:3
Blaze._createView@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1849:3
Blaze._materializeView@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1853:3
.visitObject@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1512:22
.visit@http://www.localhost.com:3000/packages/htmljs.js?567eb96d5d22631c03d6aca6afa4c42f0d1295f2:118:14
.visitArray@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1416:7
.visit@http://www.localhost.com:3000/packages/htmljs.js?567eb96d5d22631c03d6aca6afa4c42f0d1295f2:116:1
doMaterialize@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1871:30
Tracker.nonreactive@http://www.localhost.com:3000/packages/tracker.js?7f0c5481709a504dd2254ba2a71c1cee78adc280:513:12
doRender@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1869:7
viewAutorun/<@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1808:14
Blaze._withCurrentView@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12
viewAutorun@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1807:1
Tracker.Computation.prototype._compute@http://www.localhost.com:3000/packages/tracker.js?7f0c5481709a504dd2254ba2a71c1cee78adc280:296:5
Tracker.Computation@http://www.localhost.com:3000/packages/tracker.js?7f0c5481709a504dd2254ba2a71c1cee78adc280:214:5
Tracker.autorun@http://www.localhost.com:3000/packages/tracker.js?7f0c5481709a504dd2254ba2a71c1cee78adc280:487:11
Blaze.View.prototype.autorun@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1806:11
Blaze._materializeView/<@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1860:5
Tracker.nonreactive@http://www.localhost.com:3000/packages/tracker.js?7f0c5481709a504dd2254ba2a71c1cee78adc280:513:12
Blaze._materializeView@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1859:3
.visitObject@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1512:22
.visit@http://www.localhost.com:3000/packages/htmljs.js?567eb96d5d22631c03d6aca6afa4c42f0d1295f2:118:14
doMaterialize@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1871:30
Tracker.nonreactive@http://www.localhost.com:3000/packages/tracker.js?7f0c5481709a504dd2254ba2a71c1cee78adc280:513:12
doRender@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1869:7
viewAutorun/<@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1808:14
Blaze._withCurrentView@http://www.localhost.com:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12

**Comment by aldeed** [comment] 2015-01-18 04:13
Duplicate of #333

**Closed by aldeed** 2015-01-18 04:13 UTC
