### ISSUE TITLE
autoValues don't go to a collection from standard 'insert' type of form

### ISSUE THREAD

**Issue by yzalvov** [aldeed/meteor-autoform#1668] opened 2018-07-10 13:45 UTC
For `insert` type of form `autoValue`s work in a client's console, but don't save to DB. And for `update` type of form they work fine though.

Worthwhile to note:
- I don't attach any SimpleSchema to my form, just referencing to it via `schema=stepSchema` autoForm param instead. I tried to attach it, but it didn't help.
- And I give a form both `schema` and `collection` params.

As a workaround now I use my own insert logics with `onSubmit` hook and `normal` type of form.

Here's a part of my SS: 
``` JS
Schema.wizardStep1 = new SimpleSchema({
  createdAt: {
    type: Date,
    autoValue: function() {
      if (this.isInsert) {
        return new Date();
      } else if (this.isUpsert) {
        return {$setOnInsert: new Date()};
      } else {
        this.unset();
      }
    },
  },
  owner: {
    type: String,
    autoValue: () => Meteor.userId()
  }
}, { tracker: Tracker })
```

**Comment by jankapunkt** [comment] 2021-02-18 08:44
Can't reproduce. Closed. This issue may have been resolved with AutoForm 7.0.0, please migrate to the latest version and reopen in case the issue persist

**Closed as completed by jankapunkt** 2021-02-18 08:44 UTC
