### ISSUE TITLE
afFieldValueIs Helper: Cannot read property 'schema' of undefined

### ISSUE THREAD

**Issue by Ikaryas** [aldeed/meteor-autoform#753] opened 2015-03-10 12:33 UTC
I'm quite new to Meteor and I just stumbled upon this error when using the afFieldValueIs Helper:
Exception in template helper: TypeError: Cannot read property 'schema' of undefined

(I copied the tutorial from http://autoform.meteor.com/fieldvalues and it worked like a charm before the update of autoform)

kind regards

ps: sorry for my bad English :)

**Comment by aldeed** [comment] 2015-03-10 22:21
Hi please link to a reproduction repo or MeteorPad. The tutorial you link to is currently using af5 and does not have that error.

**Comment by thehopwood** [comment] 2015-03-19 00:28
I have seen this error when using afFieldIsInvalid ... not sure if legitimate bug or developer error though.

**Comment by Rongky** [comment] 2015-03-19 05:43
Also having this error after updating to af5. All caused by afFieldLabelText, afFieldIsInvalid and afFieldMessage. So I reverted back to af4.2.2 and there's no more error.

**Comment by aldeed** [comment] 2015-03-19 14:36
Can someone post full reproduction code?

**Comment by solo999** [comment] 2015-03-19 17:12
I can not reproduce it due to complicated code. But what I found (I have same error after upgrade to af5), that AutoForm.getFormSchema() return 'undefined' in parseOptions function. Hope it helps...
function parseOptions(options) {
  var hash = (options || {}).hash || {};
  // Find the form's schema
  var ss = AutoForm.getFormSchema();
  // Call getDefs for side effect of throwing errors when name is not in schema
  if (hash.name) {
    AutoForm.Utility.getDefs(ss, hash.name);
  }
  return _.extend({}, hash, {ss: ss});
}

**Comment by solo999** [comment] 2015-03-19 19:01
I have tried to reproduce it  in MeteorPad, but it works normally. The difference is MeteorPad has 1.0.2.1 version of Meteor. And I have above problem on 1.0.4.1
When I downgrade my meteor to 1.0.2.1 autoform afFieldValueIs works as a charm.
So the problem is in combination of Meteor 1.0.4.1 and af5

**Comment by shkomg** [comment] 2015-03-19 19:56
I have this poblem on Meteor 1.0.4.1  & af5.0.2

I happens with afFieldValueIs and when you have ```type="method"```

here is the link to the repo with this error reproduced: https://github.com/shkomg/autoform-demo

**Comment by shkomg** [comment] 2015-03-20 06:33
@aldeed I've posted full reproduction code in the post above.

Thank you.

**Comment by aldeed** [comment] 2015-03-20 13:37
Seems like duplicate of #790. AF isn't compatible 1.0.4.1 pending some kind of fix or solution from MDG.

**Comment by aldeed** [comment] 2015-03-20 22:53
New AF release is compatible with 1.0.4+ and should get rid of this error.

**Closed by aldeed** 2015-03-20 22:53 UTC
Labels: needs reproduction, potential bug
